printStatus(X) :- 
    (
    	printReject(X),
        write('Packet Rejected')
    );
    (   
    	not(printReject(X)),
        printDropped(X),
        write('Packet Dropped')
    );
    (
    	not(printReject(X)),
        not(printDropped(X)),
        printAccepted(X),
        write('Packet Accepted')
    ).

printReject(X) :-
    (   
    	src_ip(X,Src_IP),
    	isSrcIPRejected(Src_IP)
    );
    (   
    	dest_ip(X, Dest_IP),
        isDstIPRejected(Dest_IP)
    );
    (   
    	adapter_num(X,Adap),
        isAdapterRejected(Adap)
    );
    (   
    	protocol_type(X,Protocol),
        isProtocolIDRejected(Protocol)
    );
    (   
    	icmpv6_type(X, IC6),
        isICMPV6TypeRejected(IC6)	
    );
    (   
    	icmpv6_msgCode(X,Msg),
        isICMPV6CodeRejected(Msg)	
    );
    ( 
    	vlanId(X,VLAN),					
        isVlanIDRejected(VLAN)			
    );
    (
    	tcpSrc(X,TCPPortNo),
    	isTCPSrcRejected(TCPPortNo)
    );
    (   
    	tcpSrc(X,TCPPortNo),
    	isTCPDstRejected(TCPPortNo)
    );
    ( 
    	udpSrc(X,UDPPortNo),
   		isUDPSrcRejected(UDPPortNo) 
    );
    (   
    	udpDst(X,UDPPortNo),
   		isUDPDstRejected(UDPPortNo) 
    );
    (  
    	ipv6Src(X,IPV6SrcAddr),
   		isIPV6SrcRejected(IPV6SrcAddr) 
    );
    (   
    	ipv6Dst(X,IPV6DstAddr),
    	isIPV6DstRejected(IPV6DstAddr)
    );
    (   
    	icmpType(X,Type),
    	isICMPTypeRejected(Type)
    );
    (   
    	icmpCode(X,Code),
    	isICMPCodeRejected(Code)
    );
    (   
	protocolID(X,ID),
    	isProtocolIDRejected(ID)
    ).
printDropped(X) :-
    (   
    	src_ip(X,Src_IP),
    	isSrcIPDropped(Src_IP)
    );
    (   
    	dest_ip(X, Dest_IP),
        isDstIPDropped(Dest_IP)
    );
    (   
    	adapter_num(X,Adap),
        isAdapterDropped(Adap)
    );
    (   
    	protocol_type(X,Protocol),
        isProtocolIDDropped(Protocol)
    );
    (   
    	icmpv6_type(X, IC6),
        isICMPV6TypeDropped(IC6)	
    );
    (   
    	icmpv6_msgCode(X,Msg),
        isICMPV6CodeDropped(Msg)	
    );
    ( 
    	vlanId(X,VLAN),					
        isVlanIDDropped(VLAN)			
    );
    (
    	tcpSrc(X,TCPPortNo),
    	isTCPSrcDropped(TCPPortNo)
    );
    (   
    	tcpSrc(X,TCPPortNo),
    	isTCPDstRejected(TCPPortNo)
    );
    ( 
    	udpSrc(X,UDPPortNo),
   		isUDPSrcDropped(UDPPortNo) 
    );
    (   
    	udpDst(X,UDPPortNo),
   		isUDPDstDropped(UDPPortNo) 
    );
    (  
    	ipv6Src(X,IPV6SrcAddr),
   		isIPV6SrcDropped(IPV6SrcAddr) 
    );
    (   
    	ipv6Dst(X,IPV6DstAddr),
    	isIPV6DstDropped(IPV6DstAddr)
    );
    (   
    	icmpType(X,Type),
    	isICMPTypeDropped(Type)
    );
    (   
    	icmpCode(X,Code),
    	isICMPCodeDropped(Code)
    );
    (   
	protocolID(X,ID),
    	isProtocolIDDropped(ID)
    ).

printAccepted(_) :- true. /********** Because the default behaviour is 'accept'.*/
